# karmada-git-ssh.yaml
apiVersion: v1
kind: Secret
metadata:
  name: karmada-git-ssh
  namespace: argocd
type: Opaque
stringData:
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEY0xibGlWV0J0S2N2TkNFRGZDYkx2OUVqMmFEckZPYkE5ZFlKZHZMRWppd0FBQUpnRk1OMUNCVERkClFnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRGNMYmxpVldCdEtjdk5DRURmQ2JMdjlFajJhRHJGT2JBOWRZSmR2TEVqaXcKQUFBRUJzK2R4bVBEelduQWlybFp0NDZ2Zk5xeWZCTldYVS9RY3hNUTJsSVRKbkg5d3R1V0pWWUcwcHk4MElRTjhKc3UvMApTUFpvT3NVNXNEMTFnbDI4c1NPTEFBQUFGR0Z1TXpNMU9UUXlPRFZBWjIxaGFXd3VZMjl0QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
    -----END OPENSSH PRIVATE KEY-----
