apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-region-policy
  namespace: default
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx-region
  placement:
    clusterAffinity:
      labelSelector:
        matchExpressions:
        - key: region
          operator: In
          values:
          - korea
